baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nazmul Alom - Portfolio'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]
